headers:
  x_rapidapi_host: "hotels4.p.rapidapi.com"
  x_rapidapi_key: "16fff31242msh84d1a94fb4afb12p1430a4jsnadfa2e122da5"

urls:
  location_url: https://${headers.x_rapidapi_host}/locations/v2/search
  pricing_url: https://${headers.x_rapidapi_host}/properties/list

location_params:
  query: new york
  locale: en_US
  currency: USD

